### PR TITLE
 random-quote-machine project

### PR DESCRIPTION
**Pull request by faridafaqiri**
This pull request adds the core functionality to the random-quote-machine project, including fetching and displaying random quotes from an external API. It also introduces dynamic background color changes and integrates Twitter sharing capabilities.

Changes:

Quote Fetching:

Added fetchQuote function to fetch random quotes from the API.
The function handles network errors and updates the state with the fetched quote and author.
Background Color:

Implemented dynamic background color changes upon fetching a new quote.
Added a predefined array of colors to choose from randomly.
Error Handling:

Included error handling to display a message if the quote fetching fails.
Styling:

Updated App.css to style the quote box, text, author, and buttons.
Added hover effects for the 'New Quote' and Twitter share button.
Fixed minor CSS issues like improper capitalization and missing background color.
Twitter Integration:

Added a Twitter share button that allows users to tweet the current quote and author.

### CODE REVIEW

**Comment by Fikrat2002** [comment]
Hey,
faridafaqiri 🙋‍♀️

Great job!💯I am just impressed of your work🙌
 You've nailed all the project requirements 👏 Your feature is complete! Congratulations!!! 🎊🏆

Status: Approved ✅
Everything looks perfect, merge your project 🏆🎊👏

Highlights 💡

🏆 Successfully implemented a great design
✅ Created a professional repository with your project name
✅ Passed FreeCodeCamp requirements for the project
✅ Used Gitflow correctly by creating a development branch, setting it as default, and making commits on your feature branch
✅ Wrote meaningful commit messages
✅ Set up appropriate linter configurations based on your project's language
✅ No linter errors!
✅ Followed the task and used command-line commits
✅ Submitted a pull request from your feature branch to the development branch and shared the link for review
✅ Provided a clear and detailed description of your work in the PR
✅ Maintained clean code
✅ Created a professional README.md file in your repository
✅ The project is responsive
✅ Node.js installed
✅ React app installed
✅ npm started
✅ Deployed successfully

**Comment by faridafaqiri** [comment]
Hi!
@ahzamir 
Dear Mentor as my partner has reviewed and approved this project I am waiting for your review

**Comment by faridafaqiri** [comment]
Hi!
@ahzamir
Dear Mentor as my partner has reviewed and approved this project I am waiting for your review

**Review by ahzamir — APPROVED** [review]
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Random Quote Machine project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
